export const FETCH_FILTERED_DATA_REQUEST = "FETCH_FILTERED_DATA_REQUEST";
export const FETCH_FILTERED_DATA_SUCCESS = "FETCH_FILTERED_DATA_SUCCESS";
export const FETCH_FILTERED_DATA_FAILURE = "FETCH_FILTERED_DATA_FAILURE";
export const SELECT_MENU_ITEM = "SELECT_MENU_ITEM";