export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";

export const GET_SINGLE_PROJECT_REQUEST = "GET_SINGLE_PROJECT_REQUEST";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAIL = "GET_SINGLE_PROJECT_FAIL";

export const DELETE_SINGLE_PROJECT_REQUEST = "DELETE_SINGLE_PROJECT_REQUEST";
export const DELETE_SINGLE_PROJECT_SUCCESS = "DELETE_SINGLE_PROJECT_SUCCESS";
export const DELETE_SINGLE_PROJECT_FAIL = "DELETE_SINGLE_PROJECT_FAIL";

export const UPDATE_SINGLE_PROJECT_REQUEST = "UPDATE_SINGLE_PROJECT_REQUEST";
export const UPDATE_SINGLE_PROJECT_SUCCESS = "UPDATE_SINGLE_PROJECT_SUCCESS";
export const UPDATE_SINGLE_PROJECT_FAIL = "UPDATE_SINGLE_PROJECT_FAIL";

export const CREATE_PROJECT_CLEAR_ERROR = "CREATE_PROJECT_CLEAR_ERROR";
export const RESET_PROJECT_STATE = "RESET_PROJECT_STATE";